#!/bin/bash
set -e

# verify_pdf_conformance.sh
# Automated structural and conformance verification harness using qpdf and veraPDF
# to audit PDF outputs generated by PaperPilot.

# 1. Verify qpdf is installed
if ! command -v qpdf &> /dev/null; then
    echo "[ERROR] qpdf is not installed."
    echo "Please install it using your package manager:"
    echo "  sudo apt-get install -y qpdf   (Debian/Ubuntu)"
    echo "  brew install qpdf              (macOS)"
    exit 1
fi

echo "[INFO] qpdf found."

# 2. Check for verapdf
VERAPDF_INSTALLED=false
if command -v verapdf &> /dev/null; then
    echo "[INFO] verapdf found."
    VERAPDF_INSTALLED=true
else
    echo "[INFO] veraPDF not installed; skipping ISO PDF/A deep profile check."
fi

# Create a temporary directory for output files
TMPDIR=$(mktemp -d -t paperpilot_verify_XXXXXX)
# Clean up TMPDIR on exit
trap "rm -rf $TMPDIR" EXIT

echo "[INFO] Using temporary directory: $TMPDIR"

# Ensure we have fixtures
if [ ! -f "tests/fixtures/simple.pdf" ]; then
    echo "[ERROR] Missing test fixture tests/fixtures/simple.pdf"
    exit 1
fi

if [ ! -f "tests/fixtures/multi_page.pdf" ]; then
    echo "[ERROR] Missing test fixture tests/fixtures/multi_page.pdf"
    exit 1
fi

if [ ! -f "tests/fixtures/malformed.pdf" ]; then
    echo "[ERROR] Missing test fixture tests/fixtures/malformed.pdf"
    exit 1
fi

echo "[INFO] Building paperpilot-cli..."
cargo build -p paperpilot-cli >/dev/null 2>&1

CLI_BIN="./target/debug/paperpilot-cli"

if [ ! -x "$CLI_BIN" ]; then
    echo "[ERROR] paperpilot-cli binary not found or not executable at $CLI_BIN"
    exit 1
fi

echo "[INFO] Generating candidate PDFs..."

# Merge
$CLI_BIN merge --input tests/fixtures/simple.pdf tests/fixtures/multi_page.pdf --output $TMPDIR/merged.pdf
# Split (outputs to a directory)
$CLI_BIN split --input tests/fixtures/multi_page.pdf --pages 1 --output $TMPDIR/split_dir
# Repair (allow failure if malformed.pdf is unrecoverably corrupted)
$CLI_BIN repair --input tests/fixtures/malformed.pdf --output $TMPDIR/repaired.pdf || true
# Linearize
$CLI_BIN linearize --input tests/fixtures/simple.pdf --output $TMPDIR/linearized.pdf
# Compress
$CLI_BIN compress --input tests/fixtures/simple.pdf --quality 50 --output $TMPDIR/compressed.pdf
# PDF/A
$CLI_BIN pdf-a --input tests/fixtures/simple.pdf --output $TMPDIR/pdfa.pdf

echo "[INFO] Starting qpdf structural verification..."

CANDIDATES=("$TMPDIR/merged.pdf" "$TMPDIR/split_dir/split_1.pdf" "$TMPDIR/split_dir/split_2.pdf" "$TMPDIR/linearized.pdf" "$TMPDIR/compressed.pdf" "$TMPDIR/pdfa.pdf")
if [ -f "$TMPDIR/repaired.pdf" ]; then
    CANDIDATES+=("$TMPDIR/repaired.pdf")
fi

FAILURES=0

for pdf in "${CANDIDATES[@]}"; do
    if [ ! -f "$pdf" ]; then
        echo "[ERROR] Expected output file $pdf was not created."
        FAILURES=$((FAILURES + 1))
        continue
    fi

    echo "  Checking $pdf..."
    # --warning-exit-0 allows qpdf to exit with 0 if it only encounters warnings,
    # but it will exit with non-zero on fatal xref errors or syntax corruption.
    if ! qpdf --check --warning-exit-0 "$pdf" > /dev/null 2>&1; then
        echo "[ERROR] qpdf check failed for $pdf"
        qpdf --check --warning-exit-0 "$pdf" || true
        FAILURES=$((FAILURES + 1))
    else
        echo "  [PASS] $pdf"
    fi
done

if [ "$FAILURES" -gt 0 ]; then
    echo "[ERROR] Structural verification failed for $FAILURES document(s)."
    exit 1
fi

echo "[INFO] All qpdf structural checks passed."

if [ "$VERAPDF_INSTALLED" = true ]; then
    echo "[INFO] Starting veraPDF ISO PDF/A conformance check..."
    if [ -f "$TMPDIR/pdfa.pdf" ]; then
        if verapdf --flavour 1b --format text "$TMPDIR/pdfa.pdf"; then
            echo "  [PASS] veraPDF conformance check passed."
        else
            echo "[ERROR] veraPDF conformance check failed."
            exit 1
        fi
    else
        echo "[ERROR] PDF/A output missing, cannot run verapdf."
        exit 1
    fi
fi

echo "[SUCCESS] PDF Conformance Verification Complete."
exit 0
